### ISSUE TITLE
Unable to access Globus data

### ISSUE THREAD

**Issue by julesjacobsen** [LiuzLab/AI_MARRVEL#11]
**Describe the bug**
I'm trying to download the data from the Globus site linked to from the [README}(https://github.com/LiuzLab/AI_MARRVEL#install-required-data-dependencies)

**Expected behavior**
The download will commence and I will be able to run MARVELL-AI locally.

**Input data**
I am logged in to Globus

**Genome build**
n/a

**Screenshots or pipeline output**
```

Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector

Command Failed: Error (login)
Endpoint: aim_data_dependencies (6810458e-b702-423f-9f0c-070c1691482d)
Server: 128.249.177.10:443
Message: Login Failed
---
Details: 530-Login incorrect. : Mapping collection to specified ID failed.
530-GlobusError: v=1 c=LOGIN_DENIED
530-GridFTP-Message: Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector
530-GridFTP-JSON-Result: {
	"DATA_TYPE": "result#1.0.0",
	"code": "permission_denied",
	"detail": {
		"DATA_TYPE": "invalid_user#1.0.0",
		"usernames": [
			"u205275@ad.bcm.edu"
		]
	},
	"has_next_page": false,
	"http_response_code": 403,
	"message": "Identity set contains an identity from an allowed domain, but it does not map to a valid username for this connector"
}
530 End.      
```

**Additional context**
This has been broken for a few days now.

**Comment by ChaozhongLiu** [comment]
Hi there,

Thanks for reporting this!

We have noticed the issue of Globus and is working on transfer the big database to some other portal.
We will let you know once it finished.

Meanwhile, you can try our [web portal](https://ai.marrvel.org/) to submit the samples if you want.

**Comment by julesjacobsen** [comment]
OK, thanks for the update. Could this be a config issue at your institution's end rather than with Globus? Otherwise, are you looking at using something like [Zenodo](https://zenodo.org)?

**Comment by sasidharPasupuleti** [comment]
Hi @julesjacobsen , We are switching from globus to S3 for better access. Here are the steps to download data dependencies needed to run AIM from our AWS S3 bucket. 

1. Install awscli  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
2. enter the directory where you want your data dependencies to be dowloaded (for example in ubuntu : cd </desired/folder/path>
3. aws s3 sync s3://aim-data-dependencies-public . --no-sign-request

Hope this fixes your issue. 

Thanks

**Comment by julesjacobsen** [comment]
Thanks, all good now!
