### ISSUE TITLE
Unable to get data dependencies, not syncing with S3 bucket

### ISSUE THREAD

**Issue by Mohammed-Hamdan1** [LiuzLab/AI_MARRVEL#110]
Unable to download data dependencies using the following command:
aws s3 sync s3://aim-data-dependencies-2.0-public . --no-sign-request

command returns: "fatal error: Could not connect to the endpoint URL: "https://s3.None.amazonaws.com/aim-data-dependencies-2.0-public?list-type=2&prefix=&encoding-type=url" 

Using skyriver, not urgent at the moment (using already downloaded data)

**Comment by hyunhwan-jeong** [comment]
Hi @Mohammed-Hamdan1, do you have anything inside of your `~/.aws` directory? If so, I would recommend to rename/delete some files.

**Comment by hyunhwan-bcm** [comment]
Hi @Mohammed-Hamdan1, do you have anything inside of your ~/.aws directory? If so, I would recommend to rename/delete some files.

**Comment by hyunhwan-bcm** [comment]
We just checked the permission, we have all the permission for `--no-sign-request`, so it might be due to some issues related with your `aws-cli` or server.

**Comment by Mohammed-Hamdan1** [comment]
Thank you!

On 5 Dec 2024, at 3:24 PM, hyunhwan-bcm ***@***.***> wrote:

***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________


We just checked the permission, we have all the permission for --no-sign-request, so it might be due to some issues related with your aws-cli or server.

**Comment by jylee-bcm** [comment]
are we done with this issue?
