### ISSUE TITLE
AIM-NDG

### ISSUE THREAD

**Issue by drmurdock** [LiuzLab/AI_MARRVEL#16]
Hi, I'm interested in running AI-MARRVEL for novel gene discovery. In the manuscript, you describe running the AIM-NDG model for this purpose. Is there a specific way of running the NDG module that differs from the default instructions? Thanks.

**Comment by arine** [comment]
Hi,

Thank you for your interest in AI-MARRVEL for novel gene discovery. When you run the AIM pipeline, your input will be processed through all four models: Default mode, Recessive mode, Novel Disease Gene mode, and Novel Disease Gene + Recessive mode. The results will be saved in files named `*_default_predictions.csv`, `*_recessive_predictions.csv`, `*_nd_predictions.csv`, and `*_nd_recessive_predictions.csv` respectively. Additionally, all results will be concatenated into a single file named `*_integrated.csv`.

For more detailed information, please refer to our documentation: [AI-MARRVEL Output](https://ai-marrvel.readthedocs.io/en/latest/output.html).

Thank you.
