### ISSUE TITLE
Variant quality filter empties the VCF when users don't provide "PASS" designations

### ISSUE THREAD

**Issue by coledeisseroth** [LiuzLab/AI_MARRVEL#4]
**Describe the bug**
The variant quality filtering step requires the FILTER column in the VCF to be labeled as "PASS". If this designation is not provided in a VCF (which sometimes, it is not), AIM will throw away all of the variants.

**Expected behavior**
Filtering out the low-quality variants

**Input data**
A VCF file. In my case, the "FILTER" column of the VCF was always labeled as "."

**Genome build**
hg38--but this doesn't matter

**Screenshots or pipeline output**
I cannot give a screenshot.

**Additional context**
That is all.

**Comment by sasidharPasupuleti** [comment]
The bug has been resolved. 

Solution : if "PASS" filtering step results in zero variants ( which also means there were no variants marked "PASS" or had "." ) all variants that were input are considered for the remaining steps by AIM.
