### ISSUE TITLE
Modify exonic filtering parameters and add bed filter option

### ISSUE THREAD

**Issue by hyunhwan-bcm** [LiuzLab/AI_MARRVEL#48]
## Description
We need to make changes to the exonic filtering parameters in our Nextflow script to improve clarity and add more flexibility. This involves renaming an existing parameter and adding a new one with higher priority.

## Proposed Changes

1. Rename `--no_filter_exonic` to `--exome_filter`
2. Add a new parameter `--bed_filter`
3. Modify the filtering logic to prioritize `--bed_filter` over `--exome_filter`

### 1. Rename parameter
- Change `--no_filter_exonic` to `--exome_filter`
- Update the logic to check if `--exome_filter` is true (instead of false)

### 2. Add new parameter
- Add `--bed_filter` option
- This parameter should accept a path to a BED file for custom filtering

### 3. Modify filtering logic
- If `--bed_filter` is provided, use it for filtering regardless of `--exome_filter` setting
- If `--bed_filter` is not provided, then check `--exome_filter`
- Update the `FILTER_EXONIC` process to implement this logic

## Code Changes

Update the `FILTER_EXONIC` process (around line 53) to something like this:

## Tasks
- [ ] Rename `--no_filter_exonic` to `--exome_filter` throughout the codebase
- [ ] Add `--bed_filter` parameter to the script
- [ ] Update the `

**Comment by jylee-bcm** [comment]
Do you mean the default behavior is not performing the filtering? then it's good.

**Comment by hyunhwan-bcm** [comment]
please read the entire document carefully, this issue not only asking this but also add additional thing needs to be done. The current version the default parameter `no_filter_exonic = false`, then I believe it executes a filtering as default, isn't it?

**Comment by jylee-bcm** [comment]
Gotcha. I will work on it

**Comment by hyunhwan-bcm** [comment]
Thanks!
