### ISSUE TITLE
AIM write-protects all of the files it makes

### ISSUE THREAD

**Issue by coledeisseroth** [LiuzLab/AI_MARRVEL#6]
**Describe the bug**
When using the "True" flag that keeps AIM from deleting all of the intermediate files, the intermediate files created are write-protected in such a way that non-sudoers cannot delete them ("Permission denied"), nor can they move the directory somewhere else.

**Expected behavior**
I would like to be able to delete the intermediate files from an AIM run.

**Input data**
"rm -rf out"

**Screenshots or pipeline output**
"Permission denied"

**Comment by sasidharPasupuleti** [comment]
When running as non-root user, It's suggested to use docker with `-u` flag. This will make sure the files that are created on mounted volumes are created with the permissions and ownership of the user that issues the command. 

`eg : docker run -u $(id -u):$(id -g) <remaining_part_of_the_command>`
