### ISSUE TITLE
AWS s3 link not working

### ISSUE THREAD

**Issue by allyssonallan** [LiuzLab/AI_MARRVEL#86]
**Describe the bug**
I'd like to download the dataset to run in the HPC

**Expected behavior**
I expected to download the data but I am getting blocked due to lack of access:

`aws s3 sync s3://aim-data-dependencies-2.0-public . --no-sign-request`
>fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Input data**
Not applicable

**Genome build**
Not applicable

**Screenshots or pipeline output**
Not applicable

**Additional context**
I tried locally and inside the HPC

Thanks for your help and support!

**Comment by sasidharPasupuleti** [comment]
@allyssonallan Permissions have been fixed. You should be able to use the same command now to get the data.
`aws s3 sync s3://aim-data-dependencies-2.0-public . --no-sign-request`

**Comment by allyssonallan** [comment]
Super thanks @hyunhwan-bcm and @sasidharPasupuleti o/
