### ISSUE TITLE
HPO database updating

### ISSUE THREAD

**Issue by SpicyChicken6** [LiuzLab/AI_MARRVEL#92]
**Description**
------
We need an update for HPO database files to increase phenotype-matching performance. This includes 3 files: **hpo.obo** (structured hpo ontology), **genemap2.txt** (OMIM's Synopsis of human gene map), and **phenotype.hpoa** (MIM disease and hpos).
![image](https://github.com/user-attachments/assets/75fa4462-4a38-49d2-9b7a-90eb8aa153d6)

**Goal**
------
1. We want to update the hpo related database files for the AIM retraining.
2. The old **HPO_OMIM.tsv** file AIM has been using needs to be rebuilt from **phenotype.hpoa** file.

**Data source**
------
The newest data files are obtained from https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2024-08-13 

1. [hp-base.obo](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2024-08-13/hp-base.obo) 
2. [genemap2.txt](https://data.omim.org/downloads/E8eFWaP3SOu67gXVTVKiGA/genemap2.txt) 
3. [phenotype.hpoa](https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2024-08-13/phenotype.hpoa)

**Comment by SpicyChicken6** [comment]
commit 
39b828e

**Comment by allyssonallan** [comment]
Thanks @SpicyChicken6, inside this `hpo-base.obo` we can find [HP:6000717](https://hpo.jax.org/browse/term/HP:6000717) that I was looking for.

**Comment by SpicyChicken6** [comment]
See #93 PR
